
import scss from './styles/main.scss'
import icon_1_2 from './img/Write.png'
import icon_4 from './img/Simon says.png'
import icon_3 from './img/Search (and thou shall find).png'
import phone from './img/phone.png'
import map from './img/map.jpg'
import main from './img/main.jpg'
import bg from './img/bg.jpg'
import bg_form from './img/bg-form.jpg'
import team_1 from './img/1_team.jpg'
import team_2 from './img/2_team.jpg'
import team_3 from './img/3_team.jpg'
import team_4 from './img/4_team.jpg'
import blog_1 from './img/1_blog.jpg'
import blog_2 from './img/2_blog.jpg'
import blog_3 from './img/3_blog.jpg'
import img_1 from './img/1_img.jpg'
import img_2 from './img/2_img.jpg'


